-- ============================================================
-- bi_update.sql — auto-generated by bi_matcher.py
-- Ngày: 2026-04-26
-- Target ingredient_id: 411
-- Tổng rows: 106
-- Mapped (high/medium): 96
-- Low confidence (skipped): 1
-- Excluded (quá chung): 2
-- No match: 7
-- ============================================================

BEGIN TRANSACTION;

-- [bí đỏ → id=309] — high (6 rows)
UPDATE dish_ingredient
SET ingredient_id = 309
WHERE id IN (22193, 24635, 25169, 30005, 40927, 47012);

-- [bông bí → id=591] — high (9 rows)
UPDATE dish_ingredient
SET ingredient_id = 591
WHERE id IN (23347, 23372, 23435, 23467, 26572, 28470, 33123, 41009, 61414);

-- [bí xanh → id=910] — high (37 rows)
UPDATE dish_ingredient
SET ingredient_id = 910
WHERE id IN (
  21022, 21074, 21079, 21233, 21299, 21303, 21442, 21457, 21921, 23743,
  25097, 25364, 26073, 26269, 27012, 28347, 28361, 29439, 31379, 32179,
  32223, 34545, 35192, 35733, 39730, 40082, 40123, 43552, 45631, 48170,
  60639, 60781, 63479, 63801, 63990, 64282, 64382
);

-- [bí ngòi → id=3635] — high (33 rows)
UPDATE dish_ingredient
SET ingredient_id = 3635
WHERE id IN (
  21976, 25520, 25806, 26146, 26166, 26434, 27190, 27493, 28182, 28515,
  28719, 30230, 30436, 33197, 33864, 34421, 35903, 36920, 37586, 38857,
  41397, 43172, 44032, 45564, 46817, 47377, 48014, 49058, 50884, 50978,
  51047, 53201, 53342
);

-- [rau bí → id=6051] — high (3 rows)
UPDATE dish_ingredient
SET ingredient_id = 6051
WHERE id IN (26790, 37943, 41393);

-- [bí nụ → id=6446] — high (8 rows)
UPDATE dish_ingredient
SET ingredient_id = 6446
WHERE id IN (24510, 28394, 28532, 28548, 28557, 32483, 47538, 63987);

COMMIT;

-- ── Kiểm tra sau UPDATE ──────────────────────────────────────
SELECT ingredient_id, COUNT(*) AS remaining
FROM dish_ingredient
WHERE ingredient_id = 411
GROUP BY ingredient_id;
-- Mong đợi: giảm đúng 96 rows

-- ── SKIPPED — LOW CONFIDENCE ────────────────────────────────
-- id= 25644  raw='yellow squash bí ngòi vàng'  → 'bí ngòi'? (keyword: bí ngòi vàng)

-- ── NO MATCH — cần review thủ công ─────────────────────────
-- id= 10488  raw='bí tròn còn non'
-- id= 10507  raw='bí non'
-- id= 31393  raw='cá rô bí'
-- id= 39700  raw='bí đo'
-- id= 41772  raw='bí non'
-- id= 45678  raw='bí non'
-- id= 47562  raw='mứt bí'

-- ── EXCLUDED — raw_name quá chung, không đủ thông tin ──────
-- id=  6553  raw='bí'
-- id= 19839  raw='squash'